### ISSUE TITLE
Global method are not working

### ISSUE THREAD

**Issue by OB-GAMEDEV** [milnet92/MXTXppInterpreter#13]
First of all, I would like to thank this team for this amazing work. I hope you continue to improve and develop this work.

I found this issue, I hope you can solve it.
**When you type a global method sech as mkdate, or infolog the interpreter assume that this is undefined variable.**

Many thnaks.

**Comment by milnet92** [comment]
*Global class methods* are accesible and working as expected. What is not yet supported is:
- **Global class static methods** that act as variables like *infolog*. Although you can access them by *Global::infolog()*; This is not in my scope as of now since you can access them with the workaroud using static methods.
- **$PredefinedFunction class static methods** like *mkdate*. Some are supported like *strFmt* but some others are not. My goal is to have a general solucion that does not require implenting the methods explicitly.

**Comment by milnet92** [comment]
After a bit of digging, looks like there is a step at standard compile time that translate the $PredefinedFunctions into IL static calls to Microsoft.Dynamics.Ax.Xpp.PredefinedFunction class. 
For example, **conFind(c, value)** is translated into **Microsoft.Dynamics.Ax.Xpp.PredefinedFunctions.qfind(c, value)**.

![image](https://github.com/user-attachments/assets/1ceda2ec-0972-4f6e-b2e0-a0734138b850)

However, I did not find the actual point where this translation is done, and I don't think is worth doing. 
Currently, there is a class I created called **MXTXppPredefinedFunctions** used as a wrapper for MS *PrededefinedFunctions* class and also as a source provider for autocompletion and suggestions. I'll extend this class to incorporate the rest of the methods based on this MS resource https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-run-time-functions

**Comment by milnet92** [comment]
Predefined function definitions are now available through 8f6b0b6.

**Comment by vukisz** [comment]
@milnet92 infolog.clear(); still shows an error. Or should I just use Global::infolog().clear(); ?

**Comment by milnet92** [comment]
Yes, global variables are still pending to implement
