### ISSUE TITLE
Clarify license for Z.Expressions.Eval dependency

### ISSUE THREAD

**Issue by FH-Inway** [milnet92/MXTXppInterpreter#33]
The XppInterpreter project uses [Z.Expressions.Eval](https://www.nuget.org/packages/Z.Expressions.Eval) as dependency. The dependency is set to version [6.1.4](https://www.nuget.org/packages/Z.Expressions.Eval/6.1.4), which has been unlisted. As per https://eval-expression.net/download, that version is no longer available as a free evaluation trial.

According to https://eval-expression.net/overview#is-c-eval-expression-free, "The C# Eval Expression is free up to 50 characters or when using any [LINQ Dynamic](https://eval-expression.net/linq-dynamic) methods". Not sure if this is the case here.

While trying to build the project, I had some issues with that dependency. Only after updating it to the current version 6.1.10 and removing the explicit restriction to version 6.1.4 I was able to build the project.

It would by good if the Readme could clarify the license requirements for this dependency. I would also propose updating the dependency to a listed version.

**Comment by milnet92** [comment]
Thanks @FH-Inway for bringing this up! The library is used by the [MXT debugger](https://github.com/milnet92/MXTXppInterpreter/blob/23cfaeae274edc9ecbb9b0bbde01e0b5fec9891c/Projects/XppInterpreter/Interpreter/Debug/DebugHelper.cs#L23) to evaluate the [DebuggerDisplay](https://learn.microsoft.com/en-us/visualstudio/debugger/using-the-debuggerdisplay-attribute?view=vs-2022) attribute expressions of .NET classes. I was not taking into consideration the 50 character limitation and It can certanly be exceeded in some cases, as the expressions passed to the `Eval.execute` method is whatever is the value of the attribute.

I think It should be possible to use [Roslyn scripting](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Scripting/) but I will need to test it. Otherwise, I'll remove the debugger display expressions evaluation feature as It is only affects a small subset of classes.

**Comment by milnet92** [comment]
I discarted the idea of using Rostlyn scripting, as this generates a memory assembly that stays there forever and if not managed carefully It can cause memory leaks. However, I found a possible solution using [ExpressionEvaluator](https://github.com/codingseb/ExpressionEvaluator) which executes the code on the fly. I tested it with the scenarios in which Z.Expression.Eval would and It works. 

It has some limitations but for the purpose of this project, which is purpely to pretty print debug information, I think It's valid. Also it comes with MIT license and It has no dependencies.

**Comment by FH-Inway** [comment]
That sounds promising. Though I would consider using one of the alternatives listed in the repo, since ExpressionEvaluator does not seem to be actively maintained. Or write your own evaluator, the 4000 lines of ExpressionEvaluator looks manageable and maybe can be trimmed down further for this specific use case.

**Comment by milnet92** [comment]
The problem is that value of `DebuggerDisplayAttribute` can be literally anything form the source code language (in case of X++ dll's it's C#), so basically we need a kinda "complete" evaluation of the whole C# syntax, sadly I cannot trim ExpressionEvaluator for this reason.

After reviewing the other alternatives in the repo, all of them either compile the code (which we don't want), or are for other programming languages, or are not maintained for years... 

Considering that even Roslyn has [bugs ](https://github.com/dotnet/roslyn/issues/26054) related to the evaluation of DebuggerDisplayAttribute expressions, I wouldn't try to break our heads on this.

**Comment by milnet92** [comment]
So... after applying it to the actual project, surprise! Is slow... very slow... ~0.8s second for complex evaluations, considering that the evaluation happens 2 times for every local variable each times a breakpoint is hit is BAD.

What I did is remove the dependency and replace it with a workaround for the most clear case which is the X++ array (expression was `Size = {Size}` si that was easy.
