### ISSUE TITLE
UtcDateTime assignment error

### ISSUE THREAD

**Issue by dalabin** [milnet92/MXTXppInterpreter#34]
I've got the following error during assignment UTCDateTime edt.
![image](https://github.com/user-attachments/assets/e2e013ef-bd1a-4542-80aa-69eccc1b93e9)

**Comment by milnet92** [comment]
Thank you @dalabin for opening the issue. My guess is that the types compared here are System.DateTime and Dynamics.Ax.Xpp.AxShared.utcdatetime. The correct one should be the later since utcdatetime is the struct wraper that X++ uses. 

My guess is the type that is being assigned to "utcdatetime" keyword is incorrect (System.DateTime) and the one that is infered from DateTimeUtil::newDateTime() function is utcdatetime, which is correct.

**Comment by milnet92** [comment]
Should be fixed with 6f5bb44.
Also, implicit conversion for date and datetime were added.

Could you please try?

**Comment by dalabin** [comment]
@milnet92 , Thanks a bunch, it works perfectly!
