### ISSUE TITLE
Improvement idea - Add local methods

### ISSUE THREAD

**Issue by TrudAX** [milnet92/MXTXppInterpreter#40]
The tool works great. 
However, for more complex scenarios, it would be great to have the option to define local methods and some local variables (e.g., class declaration). Basically, make the created class the same as a "Runnable class" from Visual Studio in terms of functionality (if this is doable)

**Comment by TrudAX** [comment]
@milnet92 , oh, that is perfect, thanks for the info.

But do you think it is worth extending it to multiple methods(with this keyword)? for example the code below should generate a class with 2 method and 1 variable in classDeclaration. The purpose of this - to be able to copy 1 to 1 the code for some class from VS 
```

int num;    

int getNum()
{
    return 1;
}

int addNum(int _a, int _b)
{
    int c;
    
    c = _a + _b + this.getNum();
    
    return c;
}

num = this.addNum(2, 2);

print num;

```

**Comment by milnet92** [comment]
If the problem is to copy line by line from a *runnable class*, you can just copy and paste the content and remove the text **"this."** using the replace functionality with (Ctrl + H). It may have other problems like class declaration syntax and methods/variables accessors tho.

Doing a simple replacement works in your example:
![image](https://github.com/user-attachments/assets/07aabb37-1ca0-416e-8091-7dfd7d5ac2dd)

I'm not saying It shouldn't be added for convenience, but It's not trivial...

**Comment by TrudAX** [comment]
Ok, thanks. I think the issue can be closed
