### ISSUE TITLE
Type 'SalesTable' does not have a field named 'newMethodInSalesTableExtension'

### ISSUE THREAD

**Issue by vukisz** [milnet92/MXTXppInterpreter#48]
Hello it's me again. 
Was testing new sales table methods today and indeed as you already noticed yesterday in #47  newly added method in extension is not working on local demo VM:
![image](https://github.com/user-attachments/assets/d1152e0c-b351-40d7-9ac2-a40aa5f77098)

Question: how I can clear such cache? Tried rebuilding full model, did not help. Tried excecuting some legacy sys methods for cache clearing like flush aod and etc. But it MXTXppInterpreter still cannot see it.

In metadataProvider I can find such method, but only on extension class itself. Haven't found a quick way to enlist all table code class extensions (only table extensions works, but does not provide extended methods):
![image](https://github.com/user-attachments/assets/6ae2882f-bedc-413f-9dc6-24143c8ddf38)

Edit: you are right it's really random to reproduce, as I now I just added another method in SalesTable extension ***ReservedAmount_old_old
Now from MXTXppInterpreter side all three methods are valid ***ReservedAmount, ***ReservedAmount_old, ***ReservedAmount_old_old

**Comment by milnet92** [comment]
That's interesting, so It seems to have some sort of cache for sure!

Currently I'm using *SysDictTable.methods()*, which internally is using Accessor (Microsoft.Dynamcis.AX.Metadata.Kernel) class to retrieve the data. I didn't tried it yet, but there is a method to flush the cache specifically for table extensions that may be worth trying calling this before using the editor for the first time?

![image](https://github.com/user-attachments/assets/a2d0aa58-a91d-4188-be46-ca958c684155)

Thank you for taking the time to open the issues and giving some insights, It helps a lot :)

**Comment by milnet92** [comment]
I switched to a cloud hosted environment and now I can't reproduce the issue... I then checked with the Unified Environment and I think the problem from my end was that the code was not being pushed correctly to the online environment so that method was not actually there. I could see it locally thorugh IL inspector, but the methods were not callable in cloud because the version of the code deployed was not the same!!!! 🤦‍♂️

Could you verify please that the method is actually part of the binary that is being used? One way to do it is, after creating the extension method, use it on a RunnableClass. If the method is callable from a runnable class, then 100% should appear on the interpreter.

**Comment by vukisz** [comment]
In this image I was querying extension class metadata and listing all of its methods and that method was present and I did full model build:
![image](https://github.com/user-attachments/assets/6ae2882f-bedc-413f-9dc6-24143c8ddf38)

Anyway next time I see it I'll try to access it on runnable class.

**Comment by milnet92** [comment]
If you are using the *DiskMetadataProvider* provider on the Dev machine, it actually reads from the **source code** not from the **binaries** or **XppMetadata folder** so you could have an un-compiled method that is returned by the provider.
