### ISSUE TITLE
Improvements: Create an approval mechanism to make the tool on pair with Zero downtime function

### ISSUE THREAD

**Issue by TrudAX** [milnet92/MXTXppInterpreter#6]
One of the ideas is to make this tool on pair with the Zero downtime function in terms of security(where you have 2 users that approve the script)
On a high level I see it like this(but it is something discussable):

- Create a new mode (e.g. restrictive mode, that requires approval, it can be for example URL based and extensible)
- Create 2 fields in the script table (The user who saved the script, User who approved the script)
- Do not allow Execute script without save 
- When pressing Execute, validate that "User who approved the script" populated
- When pressing Save - clean "User who approved" field

**Comment by milnet92** [comment]
I like the Idea of having restrictions on having control on who can execute what. Do you think we can take advantage of standard workflow features? Also, I would make this as optional by default Active in production.

**Comment by TrudAX** [comment]
Thanks. 
For workflow, I don't see any reason to spend time on this; if something is so complex that it requires workflow, they will not allow your tool on the project at all. This should be just the simplest possible function to have some arguments with management or MS reviews.
Also, it should be possible to switch off it on PROD(e.g. via some code change), as for most projects it will not be required

**Comment by jofme** [comment]
Would it make sense to also implement the same temporary transaction logic as the standard custom script functionality? 

For example, the first run would abort the transaction, allowing the approver to review the dictionary changes, and then approve the script.

**Comment by TrudAX** [comment]
@jofme  - but what will be a usage scenario? if you want to implement a demo mode for your script - just introduce a variable, ask it's value in the dialog and put something like this
if (updateMode)
{
myRecord.Update()
}
else
{
info ("record AA is updated from A to B");
}
also you can run in ttsabort already 
![image](https://github.com/user-attachments/assets/28d2d78f-bb48-484d-931a-8e9fc59f0939)

**Comment by jofme** [comment]
It's an aid for the reviewer when running with the restricted mode enabled.

Let's say that the call makes additional updates, like when a project changes status; That is not caught by the info message. It would be visible for the reviewer immediately, instead of having to dig deeper into the code.

I'm aware that it could be considered bike shedding.

The use case is different from the ttsabort flag when you execute a script.

**Comment by milnet92** [comment]
@jofme What I'm understanding on what you said, basically the reviewer should execute the script in a temporary transaction. What information should we provide to the reviewer in order to analyze it's output? 

Also, the Microsoft approach to this is to execute the script once, which makes sense to have it review one time with one expected output, but for our scenario I see It difficult as the script will remain in the repository. Maybe the solution is to, for each execution that must be done to the script, a review (or approve) of the execution must be done?

**Comment by jofme** [comment]
@milnet92 I'm thinking of providing the approver with deleted, created and updated records, to know more the consequences of running a script in TEST or UAT environments.

My question is if it would make sense to have feature-parity with the Microsoft approach (and spend time on it), but I follow the point that this is not a replacement for the Microsoft solution so it might not make sense.

Approval for execution might be a bit overkill... But I think a single approval of a script is fine. That is enough for me to be comfortable installing it in my environments.

**Comment by milnet92** [comment]
Thank you both for the comments and suggestions :) Let's do something then, if someone can implement the simple approval process that @TrudAX suggested, I'll try to add the additional step of recording telemetry (no idea how yet) and executing script without database effects to report the changes to the reviewer.

**Comment by jofme** [comment]
Sounds like a plan, thanks 😊
I'm stuck at a campsite without my computer right now, but I can look at the simple approval step on Sunday if it's okay.
